intellidata/Accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse

app_name = 'Accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="Accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"editprofile/(?P<pk>\d+)/$", views.EditProfile.as_view(), name="editprofile"),
]

intellidata/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^employee/nonstandard/fileupload/$", views.EmployeeNonStdUpload.as_view(), name="nonstandardemployeefile"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^employees/", include("employees.urls", namespace="employees")),
    url(r"^employers/",include("employers.urls", namespace="employers")),
    url(r"^transmissions/",include("transmissions.urls", namespace="transmissions")),
    url(r"^events/",include("events.urls", namespace="events")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
    url(r"^bulkuploads/",include("bulkuploads.urls", namespace="bulkuploads")),
    url(r"^apicodes/",include("apicodes.urls", namespace="apicodes")),
    url(r"^emails/",include("emails.urls", namespace="emails")),
    url(r"^mandatories/",include("mandatories.urls", namespace="mandatories")),
    url(r"^numchecks/",include("numchecks.urls", namespace="numchecks")),
]

intellidata/emails/urls.py
from django.conf.urls import url

from . import views

app_name = 'emails'

urlpatterns = [
    url(r"^$", views.ListEmails.as_view(), name="all"),
    url(r"^new/$", views.CreateEmail.as_view(), name="create"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmail, name="version"),
    url(r"^search/$", views.SearchEmailForm, name="search"),
    url(r"^search/results/$", views.SearchEmailList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleEmail.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmail.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmail.as_view(),name="delete"),
]

intellidata/employees/urls.py
from django.conf.urls import url

from . import views

app_name = 'employees'

urlpatterns = [
    url(r"^$",views.ListEmployees.as_view(),name='all'),
    url(r"^(?P<pk>\d+)/$",views.SingleEmployee.as_view(),name='single'),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmployee, name="version"),
    url(r"^search/$", views.SearchEmployeesForm, name="search"),
    url(r"^search/results/$", views.SearchEmployeesList.as_view(), name="search_results"),
    url(r"^(?P<pk>\d+)/create/$",views.CreateEmployee.as_view(),name='create'),
    url(r"^(?P<pk>\d+)/employee/error/$",views.ViewEmployeeErrorList.as_view(), name='feederrors'),
    url(r"^employee/error/$",views.ViewEmployeeErrorFullList.as_view(), name='feederrorsfull'),
    url(r"^(?P<pk>\d+)/upload/$",views.BulkUploadEmployee, name='upload'),
    url(r"^upload/nonstandard/$",views.NonStdBulkUploadEmployee,name="spl_bulk"),
    url(r"^upload/nonstandard/refresh/$",views.NonStdRefresh,name="refresh"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmployee.as_view(),name='update'),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmployee.as_view(),name='delete'),
    url(r"^email/(?P<pk>\d+)/$",views.EmailEmployee, name='email'),
    url(r"^subscribe/(?P<pk>\d+)/$",views.SubscribeEmployee, name='subscribe'),
    url(r"^text/(?P<pk>\d+)/$",views.TextEmployee, name='text'),
    url(r"^rest/employeelist/$",views.EmployeeList, name="rest"),
    url(r"^(?P<pk>\d+)/rest/employeelist/$",views.EmployeeListByEmployer, name="byemployer"),
    url(r"^ods/refresh/(?P<pk>\d+)/$", views.RefreshEmployee, name="refresh"),
    url(r"^loadods/$",views.BulkUploadSOR,name="bulksor"),
    url(r"^ods/pull/(?P<pk>\d+)/$",views.BackendPull, name="backendpull"),
    url(r"^ods/history/(?P<pk>\d+)/$", views.ListEmployeesHistory, name="history"),
    url(r"^TDS/export/$",views.ExportEmployeeDataToCSV,name="employees_download"),
]

intellidata/employees/views.py
from django.contrib import messages
import datetime
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
import time
from django.db.models import Q
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from employers.models import Employer
from employees.models import Employee
from transmissions.models import Transmission
from employees.models import EmployeeError
from employees.models import EmployeeErrorSerializer
from employees.models import EmployeeErrorAggregate
from . import models
from . import forms
from employees.forms import EmployeeForm
from bulkuploads.models import BulkUpload
from bulkuploads.forms import BulkUploadForm
import boto3
from botocore.exceptions import ClientError
import json
import csv
from employers.utils import BulkCreateManager
import os.path
from os import path
from django.utils.text import slugify
import misaka
import uuid
from employers.utils import ApiDomains
from apicodes.models import APICodes
from employers.utils import Notification
import requests
from django.contrib.auth.models import User
import re
from botocore.exceptions import NoCredentialsError
import io
from django.db.models import Count
from django.utils.encoding import smart_str

from events.forms import EventForm
from events.models import Event
from mandatories.models import Mandatory
from numchecks.models import Numcheck
from datetime import datetime

# For Rest rest_framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from employees.serializers import EmployeeSerializer


class SingleEmployee(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'employee_details'
    model = models.Employee
    template_name = 'employees/employee_detail.html'
    #form_class = forms.employeeForm

class ListEmployees(LoginRequiredMixin, generic.ListView):
    context_object_name = 'employee_list'
    model = models.Employee
    template_name = 'employees/employee_list.html'

    #form_class = forms.employeeForm

    def get_queryset(self):
    #    return employee.objects.filter(employer=employer_name)
    #    return employee.objects.all
        return models.Employee.objects.prefetch_related('employer')


class CreateEmployee(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    #fields = ("name", "age")
    permission_required = 'employees.add_employee'
    template_name = 'employees/employee_form.html'
    context_object_name = 'employee_details'
    redirect_field_name = 'employees/employee_detail.html'
    model = models.Employee
    form_class = forms.EmployeeForm

    def dispatch(self, request, *args, **kwargs):
        """
        Overridden so we can make sure the `Employer` instance exists
        before going any further.
        """
        self.employer = get_object_or_404(models.Employer, pk=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        if not self.request.user.has_perm('employees.add_employee'):
            raise HttpResponseForbidden()
        else:
            """
            Overridden to add the employer relation to the `Employee` instance.
            """
            form.instance.creator = self.request.user
            form.instance.record_status = "Created"
            form.instance.source = "Online Transaction"
            form.instance.employerid=self.employer.employerid

            email_addr = form.instance.email
            phone_num = form.instance.mobile_phone

            #NOTIFY Employee
            notification = Notification()
            subscription_arn = notification.SubscribeEmployeeObj(phone_num)

            #Log events
            event = Event()
            event.EventTypeCode = "SUB"
            event.EventSubjectId = ""
            event.EventSubjectName = phone_num
            event.EventTypeReason = "Auto subscribed for push notification"
            event.source = "Online Transaction"
            event.creator=self.request.user
            event.save()

            notification.TextEmployeeObj(subscription_arn)

            #Log events
            event = Event()
            event.EventTypeCode = "SMS"
            event.EventSubjectId = ""
            event.EventSubjectName = ""
            event.EventTypeReason = "Auto push notification sent for the below auto subscription"
            event.source = "Online Transaction"
            event.creator=self.request.user
            event.save()


            notification.EmailEmployeeObj(email_addr)

            #Log events
            event = Event()
            event.EventTypeCode = "EML"
            event.EventSubjectId = ""
            event.EventSubjectName = email_addr
            event.EventTypeReason = "Auto email notification sent"
            event.source = "Online Transaction"
            event.creator=self.request.user
            event.save()

            form.instance.sms = "Initial notification sent"
            form.instance.emailer = "Initial notification sent"

            form.instance.employer = self.employer

            return super().form_valid(form)

#Pull from  backend system of record(SOR)
@permission_required("employees.add_employee")
@login_required
def BackendPull(request, pk):
        # fetch the object related to passed id

        employee_obj = get_object_or_404(Employee, pk = pk)

        api = ApiDomains()
        url = api.employee + "/" + "latest"
        payload={'ident': employee_obj.employeeid}
        resp = requests.get(url, params=payload)
        print(resp.text)
        print(resp.status_code)
        obj = get_object_or_404(APICodes, http_response_code = resp.status_code)
        status_message=obj.http_response_message
        mesg=str(resp.status_code) + " - " + status_message
        if resp.status_code != 200:
            # This means something went wrong.
            #raise ApiError('GET /tasks/ {}'.format(resp.status_code))
            #raise APIError(resp.status_code)
            message={'messages':mesg}
            return render(request, "messages.html", context=message)
        else:
            json_data = json.loads(resp.text)

            # fetch the object related to passed id

            #OVERRIDE THE OBJECT WITH API data
            obj.pk = int(json_data["LOCAL_ID"])
            obj.employeeid = json_data["EMPLOYEE_ID"]
            obj.ssn = json_data["SSN"]
            obj.name = json_data["NAME"]
            obj.name_html = misaka.html(obj.name)
            obj.gendercode = json_data["GENDERCODE"]
            obj.age = json_data["AGE"]
            obj.birthdate = json_data["BIRTHDATE"]
            obj.maritalstatus = json_data["MARITALSTATUS"]

            obj.home_address_line_1 = json_data["HOME_ADDRESS_LINE_1"]
            obj.home_address_line_2 = json_data["HOME_ADDRESS_LINE_2"]
            obj.home_city = json_data["HOME_CITY"]
            obj.home_state = json_data["HOME_STATE"]
            obj.home_zipcode = json_data["HOME_ZIPCODE"]

            obj.mail_address_line_1 = json_data["MAIL_ADDRESS_LINE_1"]
            obj.mail_address_line_2 = json_data["MAIL_ADDRESS_LINE_2"]
            obj.mail_city = json_data["MAIL_CITY"]
            obj.mail_state = json_data["MAIL_STATE"]
            obj.mail_zipcode = json_data["MAIL_ZIPCODE"]

            obj.work_address_line_1 = json_data["WORK_ADDRESS_LINE_1"]
            obj.work_address_line_2 = json_data["WORK_ADDRESS_LINE_2"]
            obj.work_city = json_data["WORK_CITY"]
            obj.work_state = json_data["WORK_STATE"]
            obj.work_zipcode = json_data["WORK_ZIPCODE"]

            obj.email = json_data["EMAIL"]
            obj.alternate_email = json_data["ALTERNATE_EMAIL"]

            obj.home_phone = json_data["HOME_PHONE"]
            obj.work_phone = json_data["WORK_PHONE"]
            obj.mobile_phone = json_data["MOBILE_PHONE"]

            obj.enrollment_method = json_data["ENROLLMENT_METHOD"]

            obj.employment_information = json_data["EMPLOYMENT_INFORMATION"]

            employer_id = json_data["EMPLOYER"]
            employer_obj = get_object_or_404(Employer, pk = employer_id)
            obj.employer = employer_obj

            obj.source = json_data["SOURCE"]
            obj.employerid = json_data["EMPLOYERID"]

            obj.creator = User.objects.get(pk=int(json_data["CREATOR"]))
            obj.employee_date = json_data["EMPLOYEE_DATE"]

            obj.sms = json_data["SMS"]
            obj.emailer = json_data["EMAILER"]
            obj.artefact = json_data["ARTEFACT"]

            obj.backend_SOR_connection = json_data["CONNECTION"]
            obj.response = json_data["RESPONSE"]
            obj.commit_indicator = json_data["COMMIT_INDICATOR"]
            obj.record_status = json_data["RECORD_STATUS"]

            context = {'employee_details':obj}

            return render(request, "employees/employee_detail.html", context=context)



#Pull from  backend system of record(SOR)
@permission_required("employees.add_employee")
@login_required
def ListEmployeesHistory(request, pk):

                context ={}

                employee_obj = get_object_or_404(Employee, pk = pk)

                api = ApiDomains()
                url = api.employee + "/" + "history"

                payload={'ident': employee_obj.employeeid}

                resp = requests.get(url, params=payload)
                print(resp.status_code)

intellidata/employees/templates/employees/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'employers:all' %}" class="btn btn-simple">Employers</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'employees:all' %}" class="btn btn-simple">employees</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

</html>

intellidata/employees/templates/employees/employee_base.html
{% extends "base.html" %}


{% block content %}


<div class="container">
  <div class="row">
    {% block preemployee %}{% endblock %}
    {% block employee_content %}{% endblock %}
    {% block postemployee %}{% endblock %}
  </div>
</div>

{% endblock %}

intellidata/employees/templates/employees/employee_detail.html
{% extends "employees/employee_base.html" %}

{% block preemployee %}

  <div class="dropdown">
    <button class="dropbtn btn btn-primary btn-large">Manage employee</button>
    <div class="dropdown-content">

    <a href="{% url 'employees:version' pk=employee_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version employee</a>
    &nbsp;
    <a href="{% url 'employees:update' pk=employee_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update employee</a>
    &nbsp;
    <a href="{% url 'employees:delete' pk=employee_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete employee</a>
    &nbsp;

    </div>
  </div>


  <div class="dropdown">
    <button class="dropbtn btn btn-primary btn-large">Notify employee</button>
    <div class="dropdown-content">

    <a href="{% url 'employees:email' pk=employee_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-envelope"></span> Email employee</a>
    &nbsp;
    <a href="{% url 'employees:subscribe' pk=employee_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-phone"></span> Subscribe employee</a>
    &nbsp;
    <a href="{% url 'employees:text' pk=employee_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-phone"></span> Text employee</a>
    &nbsp;

    </div>
  </div>

  &nbsp;
  <a href="{% url 'employees:backendpull' pk=employee_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Pull From ODS</a>
  &nbsp;
  <a href="{% url 'employees:history' pk=employee_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> List History</a>
  &nbsp;
  <a href="{% url 'employees:refresh' pk=employee_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-refresh"></span> Refresh From ODS</a>
  &nbsp;
  <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
  &nbsp;

{% endblock %}


{% block postemployee %}

  <div class="container">
    <h1>{{employee_details.name}}</h1>
    <h2>Employee ID: {{employee_details.employeeid}}</h2>
    <h2>SSN: {{employee_details.ssn}}</h2>
    <h2>Gender: {{employee_details.gendercode}}</h2>
    <h2>Age: {{employee_details.age}}</h2>
    <h2>Birthdate: {{employee_details.birthdate}}</h2>
    <h2>Employer: {{employee_details.employer}}</h2>
    <h2>Employer ID: {{employee_details.employerid}}</h2>
    <h2>Marital Status: {{employee_details.maritalstatus}}</h2>

    <h2>Email: {{employee_details.email}}</h2>
    <h2>Alternate Email: {{employee_details.alternate_email}}</h2>

    <h2>Home Phone: {{employee_details.home_phone}}</h2>
    <h2>Work Phone: {{employee_details.work_phone}}</h2>
    <h2>Mobile Phone: {{employee_details.mobile_phone}}</h2>

    <h2>Enrollment Method: {{employee_details.enrollment_method}}</h2>
    <h2>Employment Information: {{employee_details.employment_information}}</h2>

  </div>
  &nbsp;
  <div class="container">
    <h2>Home Address Line 1: {{employee_details.home_address_line_1}}</h2>
    <h2>Home Address Line 2: {{employee_details.home_address_line_2}}</h2>
    <h2>Home City: {{employee_details.home_city}}</h2>
    <h2>Home State: {{employee_details.home_state}}</h2>
    <h2>Home Zipcode: {{employee_details.home_zipcode}}</h2>
  </div>
  &nbsp;
  <div class="container">
    <h2>Mail Address Line 1: {{employee_details.mail_address_line_1}}</h2>
    <h2>Mail Address Line 2: {{employee_details.mail_address_line_2}}</h2>
    <h2>Mail City: {{employee_details.mail_city}}</h2>
    <h2>Mail State: {{employee_details.mail_state}}</h2>
    <h2>Mail Zipcode: {{employee_details.mail_zipcode}}</h2>
  </div>
  &nbsp;
  <div class="container">
    <h2>Work Address Line 1: {{employee_details.work_address_line_1}}</h2>
    <h2>Work Address Line 2: {{employee_details.work_address_line_2}}</h2>
    <h2>Work City: {{employee_details.work_city}}</h2>
    <h2>Work State: {{employee_details.work_state}}</h2>
    <h2>Work Zipcode: {{employee_details.work_zipcode}}</h2>
  </div>
  &nbsp;
  <div class="container">
    <h2>Created On: {{employee_details.employee_date}}</h2>
    <h2>Created By: {{employee_details.creator}}</h2>
    <h2>SMS Sent: {{employee_details.sms}}</h2>
    <h2>EMAIL Sent: {{employee_details.emailer}}</h2>

    <h2>Artefacts: <a href={{employee_details.artefact.url}}>View Document</a></h2>
  </div>
    &nbsp;
  <div class="container">
    <h2>Orgin: {{employee_details.source}}</h2>
    <h2>Bulk Upload Indicator: {{employee_details.bulk_upload_indicator}}</h2>
    <h2>ODS Connection: {{employee_details.backend_SOR_connection}}</h2>
    <h2>Commit Indicator: {{employee_details.commit_indicator}}</h2>
    <h2>Record Status: {{employee_details.record_status}}</h2>
    <h2>Response: {{employee_details.response}}</h2>
  </div>

{% endblock %}

intellidata/employees/templates/employees/employee_form.html
{% extends "employees/employee_base.html" %}
{% load bootstrap3 %}

{% block employee_content %}

<h4>Edit Employee</h4>
  <form method="POST" enctype="multipart/form-data">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Save" class="btn btn-primary btn-large">
    &nbsp;
    <a href="{% url 'employees:all'%}" class="btn btn-primary btn-large">Cancel</a>
  </form>

{% endblock %}

intellidata/employees/templates/employees/employee_list copy.html
{% extends "employees/employee_base.html" %}

{% block preemployee %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			{{user.username }}
		</h2>

    {% endif %}
			<h2>Employees</h2>

			<p>Welcome to the Employees Page! Select a Employee that you want to work on!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'employees:create' pk=group.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New employee!</a>
	{% endif %}
</div>
{% endblock %}

{% block employee_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for employee in object_list %}
		  <a class="list-group-item" href="{% url 'employee:single' pk=employee.pk %}">
			     <h3 class="title list-group-item-heading">{{ employee.name }}</h3>
					 <h3 class="title list-group-item-heading">Age: {{ employee.age }}</h3>
					 <h3 class="title list-group-item-heading">Group: {{ employee.group }}</h3>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

intellidata/employees/templates/employees/employee_list.html
{% extends "employees/employee_base.html" %}

{% block preemployee %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome
			{{user.username }}
		</h2>
    {% endif %}

		<h2>Employees</h2>

		{% if not object_list %}
  			<p>No employees available at this time! Go back and add a employee to this group!</p>
		{% else %}
				<p>Welcome to the Employees Page! Select a employee that you want to work on!</p>
		{% endif %}

		<br>
		<div class="dropdown">
		  <button class="dropbtn btn btn-primary btn-large">Manage Employees</button>
		  <div class="dropdown-content">
		  	<a href="{% url 'employees:spl_bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-up"></span>Upload Non-Standard Data</a>
				&nbsp
				<a href="{% url 'employees:refresh' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span>Ingest Non-Standard Data</a>
				&nbsp
				<a href="{% url 'employees:employees_download' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span> Download Employees!</a>
				&nbsp;
				<a href="{% url 'employees:feederrorsfull' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span>View Errors</a>
			</div>
		</div>
		&nbsp
		<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">

	</div>
</div>
{% endblock %}

{% block employee_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for employee in object_list %}
		  <a class="list-group-item" href="{% url 'employees:single' pk=employee.pk %}">
			     <h3 class="title list-group-item-heading">{{ employee.name }}</h3>
					 <h4 class="title list-group-item-heading">Employee ID: {{ employee.employeeid }}</h4>
					 <h4 class="title list-group-item-heading">Age: {{ employee.age }}</h4>
					 <h4 class="title list-group-item-heading">Email: {{ employee.email }}</h4>
					 <h4 class="title list-group-item-heading">Phone: {{ employee.mobile_phone }}</h4>
					 &nbsp;
					 <h4 class="title list-group-item-heading">Employer: {{ employee.employer }}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ employee.employee_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ employee.creator }}</h4>
					 <h4 class="title list-group-item-heading">Bulk Upload Indicator: {{employee.bulk_upload_indicator}}</h4>

		  </a>
		{% endfor %}
	</div>
</div>
{% endblock %}