intellidata/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^employee/nonstandard/fileupload/$", views.EmployeeNonStdUpload.as_view(), name="nonstandardemployeefile"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^employees/", include("employees.urls", namespace="employees")),
    url(r"^employers/",include("employers.urls", namespace="employers")),
    url(r"^transmissions/",include("transmissions.urls", namespace="transmissions")),
    url(r"^events/",include("events.urls", namespace="events")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
    url(r"^bulkuploads/",include("bulkuploads.urls", namespace="bulkuploads")),
    url(r"^apicodes/",include("apicodes.urls", namespace="apicodes")),
    url(r"^emails/",include("emails.urls", namespace="emails")),
    url(r"^mandatories/",include("mandatories.urls", namespace="mandatories")),
    url(r"^numchecks/",include("numchecks.urls", namespace="numchecks")),
]

intellidata/emails/urls.py
from django.conf.urls import url

from . import views

app_name = 'emails'

urlpatterns = [
    url(r"^$", views.ListEmails.as_view(), name="all"),
    url(r"^new/$", views.CreateEmail.as_view(), name="create"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmail, name="version"),
    url(r"^search/$", views.SearchEmailForm, name="search"),
    url(r"^search/results/$", views.SearchEmailList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleEmail.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmail.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmail.as_view(),name="delete"),
]

intellidata/transmissions/urls.py
from django.conf.urls import url

from . import views

app_name = 'transmissions'

urlpatterns = [
    url(r"^$", views.ListTransmissions.as_view(), name="all"),
    url(r"^ods/history/(?P<pk>\d+)/$", views.ListTransmissionsHistory, name="history"),
    url(r"^ods/refresh/(?P<pk>\d+)/$", views.RefreshTransmission, name="refresh"),
    url(r"^new/$", views.CreateTransmission.as_view(), name="create"),
    url(r"^bulkupload/$",views.BulkUploadTransmission,name="bulk"),
    url(r"^bulkuploadods/$",views.BulkUploadSOR,name="bulksor"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionTransmission, name="version"),
    url(r"^ods/pull/(?P<pk>\d+)/$",views.BackendPull, name="backendpull"),
    url(r"^search/$", views.SearchTransmissionsForm, name="search"),
    url(r"^search/results/$", views.SearchTransmissionsList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleTransmission.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateTransmission.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteTransmission.as_view(),name="delete"),
    url(r"^transmission/error/$",views.ViewTransmissionErrorList.as_view(), name='feederrors'),
    url(r"^(?P<pk>\d+)/employers/show/$", views.ShowEmployersList.as_view(), name="show_employers"),
    url(r"^TDS/export/$", views.ExportTransmissionDataToCSV, name="export_transmissions"),

    url(r"^rest/transmissionlist/$",views.TransmissionList, name="rest"),
    url(r"^rest/transmissionlist/parms/$",views.TransmissionListByParm, name="transmissionsbyparms"),
    url(r"^rest/transmissionlist/(?P<pk>\d+)/$",views.TransmissionListByID, name="databytransmission"),
    url(r"^rest/employerlist/(?P<pk>\d+)/$",views.EmployerListByID, name="databyemployer"),

]

intellidata/transmissions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Transmission
from .models import TransmissionError


TRANSMISSION_CHOICES=[('Connected','Connected'),
     ('Disconnected','Disconnected')
     ]

class TransmissionForm(forms.ModelForm):

    transmissionid: forms.TextInput(attrs={'readonly':'readonly'})

    backend_SOR_connection = forms.ChoiceField(choices=TRANSMISSION_CHOICES, widget=forms.RadioSelect, label='If connected to ODS')
    commit_indicator = forms.CharField(required=False, label='If this transmission data is sync-ed up with ODS', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    record_status = forms.CharField(required=False, label='If this transmission data got Created or Updated', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    response = forms.CharField(required=False, label='Connection response from/to ODS', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    source = forms.CharField(required=False, label='Origin', widget=forms.TextInput(attrs={'readonly':'readonly'}))

    class Meta:
        model = Transmission

        exclude = ('creator', 'bulk_upload_indicator')

        widgets = {

            'transmissionid': forms.TextInput(attrs={'readonly':'readonly'}),

            'SenderName': forms.TextInput(attrs={'class': 'textinputclass'}),

            'BenefitAdministratorPlatform': forms.TextInput(attrs={'class': 'textinputclass'}),

            'ReceiverName': forms.TextInput(attrs={'class': 'textinputclass'}),

            'TestProductionCode': forms.TextInput(attrs={'class': 'textinputclass'}),

            'TransmissionTypeCode': forms.TextInput(attrs={'class': 'textinputclass'}),

            'SystemVersionIdentifier': forms.TextInput(attrs={'class': 'textinputclass'}),

            'planadmin_email_address': forms.EmailField(max_length = 200),

        }

class TransmissionErrorForm(forms.ModelForm):

    serial = forms.CharField(required=False, label='Serial#', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    name = forms.CharField(required=False, label='Transmission Name', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    errorfield = forms.CharField(required=False, label='Field At Error', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    error_description = forms.CharField(required=False, label='Error description_html', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    source = forms.CharField(required=False, label='Origin', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    #error_date = forms.DateTimeField(required=False, label='Feed Date', widget=forms.TextInput(attrs={'readonly':'readonly'}))

    class Meta:
        model = TransmissionError

        #fields = ('serial', 'name', 'errorfield', 'description', 'group', 'error_date')
        exclude = ()

        widgets = {
            'creator': forms.TextInput(attrs={'readonly':'readonly'}),
        }

intellidata/transmissions/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.decorators import user_passes_test
import time
from django.db.models import Q
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.db.models import Count
from employers.models import Employer, EmployerSerializer
from employees.models import Employee, EmployeeSerializer
from products.models import Product
from django.contrib.auth.models import User
from bulkuploads.models import BulkUpload
from apicodes.models import APICodes
from transmissions.models import Transmission
from transmissions.models import TransmissionError
from transmissions.models import TransmissionErrorSerializer
from transmissions.models import TransmissionErrorAggregate
from . import models
from . import forms
from transmissions.forms import TransmissionForm
from bulkuploads.forms import BulkUploadForm
import csv
from employers.utils import BulkCreateManager
from employers.utils import ApiDomains
import os.path
from os import path
from django.utils.text import slugify
import misaka
import uuid
from django.shortcuts import get_object_or_404
from events.forms import EventForm
from events.models import Event

import boto3
import requests
import json
import re
from botocore.exceptions import NoCredentialsError
import io
from django.db.models import Count

from django.forms.models import model_to_dict
from django.utils.encoding import smart_str
from mandatories.models import Mandatory
from numchecks.models import Numcheck


# For Rest rest_framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from transmissions.serializers import TransmissionSerializer
from employers.serializers import EmployerSerializer
from employees.serializers import EmployeeSerializer
from products.serializers import ProductSerializer

from rest_framework import serializers

class SingleTransmission(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'transmission_details'
    model = models.Transmission
    template_name = 'transmissions/transmission_detail.html'

class ListTransmissions(LoginRequiredMixin, generic.ListView):
    model = models.Transmission
    template_name = 'transmissions/transmission_list.html'

    def get_queryset(self):
        return models.Transmission.objects.all()
        #return models.transmission.objects.get(user=request.user)


class CreateTransmission(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
#    fields = ("name", "description")
    permission_required = 'transmissions.add_transmission'
    context_object_name = 'transmission_details'
    redirect_field_name = 'transmissions/transmission_list.html'
    form_class = forms.TransmissionForm
    model = models.Transmission
    template_name = 'transmissions/transmission_form.html'

    def form_valid(self, form):
        if not self.request.user.has_perm('transmissions.add_transmission'):
            raise HttpResponseForbidden()
        else:
            form.instance.creator = self.request.user
            form.instance.record_status = "Created"
            form.instance.source = "Online Transaction"

            return super().form_valid(form)


#Pull from  backend system of record(SOR)
@permission_required("transmissions.add_transmission")
@login_required
def BackendPull(request, pk):
        # fetch the object related to passed id
        #url = 'https://94q78vev60.execute-api.us-east-1.amazonaws.com/Prod/intellidataTransmissionAPI/latest'

        prod_obj = get_object_or_404(Transmission, pk = pk)

        api = ApiDomains()
        url = api.transmission + "/" + "latest"
        payload={'ident': prod_obj.transmissionid}
        resp = requests.get(url, params=payload)
        print(resp.text)
        print(resp.status_code)
        obj = get_object_or_404(APICodes, http_response_code = resp.status_code)
        status_message=obj.http_response_message
        mesg=str(resp.status_code) + " - " + status_message
        if resp.status_code != 200:
            # This means something went wrong.
            #raise ApiError('GET /tasks/ {}'.format(resp.status_code))
            #raise APIError(resp.status_code)
            message={'messages':mesg}
            return render(request, "messages.html", context=message)
        else:
            json_data = json.loads(resp.text)

            # fetch the object related to passed id
            #obj = get_object_or_404(Transmission, pk = json_data["LOCAL_ID"])

            # pass the object as instance in form
            #form = TransmissionForm(request.POST or None, instance = obj)

            #OVERRIDE THE OBJECT WITH API data
            obj.pk = int(json_data["LOCAL_ID"])
            obj.transmissionid = json_data["TRANSMISSION_ID"]
            obj.SenderName = json_data["SENDER_NAME"]
            obj.BenefitAdministratorPlatform = json_data["BENEFIT_ADMINISTRATOR_PLATFORM"]
            obj.ReceiverName = json_data["RECEIVER_NAME"]

            obj.TestProductionCode = json_data["TEST_PRODUCTION_CODE"]
            obj.TransmissionTypeCode = json_data["TRANSMISSION_TYPE_CODE"]
            obj.SystemVersionIdentifier = json_data["SYSTEM_VERSION_IDENTIFIER"]
            #obj.planadmin_email = json_data["PLANADMIN_EMAIL"]
            #obj.planadmin_email = json_data.get("PLANADMIN_EMAIL")
            obj.planadmin_email = json_data.get("PLANADMIN_EMAIL")
            obj.creator = User.objects.get(pk=int(json_data["CREATOR"]))
            #obj.crerator = get_object_or_404(User, pk=obj.creatorid)
            obj.create_date = json_data["CREATE_DATE"]
            obj.backend_SOR_connection = json_data["CONNECTION"]
            obj.response = json_data["RESPONSE"]
            obj.commit_indicator = json_data["COMMIT_INDICATOR"]
            obj.record_status = json_data["RECORD_STATUS"]

            context = {'transmission_details':obj}

            return render(request, "transmissions/transmission_detail.html", context=context)



#Pull from  backend system of record(SOR)
@permission_required("transmissions.add_transmission")
@login_required
def ListTransmissionsHistory(request, pk):

                context ={}

                prod_obj = get_object_or_404(Transmission, pk = pk)

                api = ApiDomains()
                url = api.transmission + "/" + "history"
                #url = 'https://94q78vev60.execute-api.us-east-1.amazonaws.com/Prod/intellidatatransmissionAPI/history'
                payload={'ident': prod_obj.transmissionid}

                resp = requests.get(url, params=payload)
                print(resp.status_code)
                obj = get_object_or_404(APICodes, http_response_code = resp.status_code)
                status_message=obj.http_response_message
                mesg=str(resp.status_code) + " - " + status_message

                if resp.status_code != 200:
                    # This means something went wrong.
                    #raise ApiError('GET /tasks/ {}'.format(resp.status_code))
                    #raise APIError(resp.status_code)
                    message={'messages':mesg}
                    return render(request, "messages.html", context=message)
                else:
                    json_data=[]
                    dict_data=[]
                    obj_data=[]
                    json_data = resp.json()

                    #print(json_data[0])
                    #print(json_data[1])
                    for ix in range(len(json_data)):
                     obj = Transmission()
                      #dict_data.append(json.loads(json_data[ix]))
                     obj.pk = int(json_data[ix]["LOCAL_ID"])
                     obj.transmissionid = json_data[ix]["TRANSMISSION_ID"]
                     obj.SenderName = json_data[ix]["SENDER_NAME"]
                     obj.BenefitAdministratorPlatform = json_data[ix]["BENEFIT_ADMINISTRATOR_PLATFORM"]
                     obj.ReceiverName = json_data[ix]["RECEIVER_NAME"]

                     obj.TestProductionCode = json_data[ix]["TEST_PRODUCTION_CODE"]
                     obj.TransmissionTypeCode = json_data[ix]["TRANSMISSION_TYPE_CODE"]
                     obj.SystemVersionIdentifier = json_data[ix]["SYSTEM_VERSION_IDENTIFIER"]
                     #obj.planadmin_email = json_data[ix]["PLANADMIN_EMAIL"]
                     obj.planadmin_email = json_data[ix].get("PLANADMIN_EMAIL")
                     #obj.photo = json_data[ix]["PHOTO"]
                     obj.creator = User.objects.get(pk=int(json_data[ix]["CREATOR"]))
                     obj.create_date = json_data[ix]["CREATE_DATE"]
                     obj.backend_SOR_connection = json_data[ix]["CONNECTION"]
                     obj.response = json_data[ix]["RESPONSE"]
                     obj.record_status = json_data[ix]["RECORD_STATUS"]
                     obj.commit_indicator = json_data[ix]["COMMIT_INDICATOR"]

                     obj_data.append(obj)

                    context = {'object_list':obj_data}

                    return render(request, "transmissions/transmission_list.html", context=context)

                    #mesg_obj = get_object_or_404(APICodes, http_response_code = 1000)
                    #status_message=mesg_obj.http_response_message
                    #mesg="1000" + " - " + status_message
                    # add form dictionary to context
                    #message={'messages':mesg}

intellidata/transmissions/templates/transmissions/transmission_detail.html
{% extends "transmissions/transmission_base.html" %}
{% load static %}
{% block pretransmission %}

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Transmissions</button>
  <div class="dropdown-content">

  <a href="{% url 'transmissions:version' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version transmission</a>
  &nbsp;
  <a href="{% url 'transmissions:update' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update transmission</a>
  &nbsp;
  <a href="{% url 'transmissions:delete' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete transmission</a>
  &nbsp;
  <a href="{% url 'transmissions:backendpull' pk=transmission_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Pull From ODS</a>
  &nbsp;
  <a href="{% url 'transmissions:history' pk=transmission_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> List History</a>
  &nbsp;
  <a href="{% url 'transmissions:refresh' pk=transmission_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Refresh From ODS</a>
  &nbsp;
  <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
  &nbsp;
  </div>
</div>

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Employer</button>
  <div class="dropdown-content">

    <a href="{% url 'transmissions:show_employers' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span>Show Employers</a>
    &nbsp;

  </div>
</div>

<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
&nbsp;


<h1>Sender Name: {{transmission_details.SenderName}}</h1>
<h2>PK: {{transmission_details.pk}}</h2>
<h2>ID: {{transmission_details.transmissionid}}</h2>
<h2>Benefit Administrator Platform: {{transmission_details.BenefitAdministratorPlatform}}</h2>
<h2>Receiver Name: {{transmission_details.ReceiverName}}</h2>
<h2>Test Production Code: {{transmission_details.TestProductionCode}}</h2>
<h2>Transmission Type Code: {{transmission_details.TransmissionTypeCode}}</h2>
<h2>System Version Identifier: {{transmission_details.SystemVersionIdentifier}}</h2>
<h2>Plan Admin's Email Address: {{transmission_details.planadmin_email}}</h2>
<h2>Created On: {{transmission_details.create_date}}</h2>
<h2>Created By: {{transmission_details.creator}}</h2>
<h2>Origin: {{transmission_details.source}}</h2>
<h2>Bulk Upload Indicator: {{transmission_details.bulk_upload_indicator}}</h2>
<h2>ODS Connection: {{transmission_details.backend_SOR_connection}}</h2>
<h2>Commit Indicator: {{transmission_details.commit_indicator}}</h2>
<h2>Record Status: {{transmission_details.record_status}}</h2>
<h2>Response: {{transmission_details.response}}</h2>

{% for message in messages %}

        <div class="alert alert-success">
            <a class="close" href="#" data-dismiss="alert">×</a>

            {{ message }}

        </div>
{% endfor %}

{% endblock %}

intellidata/transmissions/templates/transmissions/transmission_detail1.html
{% extends "transmissions/transmission_base.html" %}
{% load static %}
{% block pretransmission %}

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Transmissions</button>
  <div class="dropdown-content">

  <a href="{% url 'transmissions:version' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version transmission</a>
  &nbsp;
  <a href="{% url 'transmissions:update' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update transmission</a>
  &nbsp;
  <a href="{% url 'transmissions:delete' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete transmission</a>
  &nbsp;
  <a href="{% url 'transmissions:backendpull' pk=transmission_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Pull From Backend</a>
  &nbsp;
  <a href="{% url 'transmissions:history' pk=transmission_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> List History</a>
  &nbsp;
  <a href="{% url 'transmissions:refresh' pk=transmission_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Refresh From Backend</a>
  &nbsp;
  <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
  &nbsp;
  </div>
</div>

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Employer</button>
  <div class="dropdown-content">

    <a href="{% url 'transmissions:show_employers' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span>Show Employers</a>
    &nbsp;
    <a href="{% url 'employers:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span>Add Employer</a>
    &nbsp;
    <a href="{% url 'employers:bulk' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-upload"></span>Upload Employer</a>
    &nbsp;
    <a href="{% url 'employers:bulksor' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-upload"></span>Load To ODS</a>
    &nbsp;
    <a href="{% url 'employers:feederrors' pk=transmission_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-fire"></span>View Feed Errors</a>
    &nbsp;

  </div>
</div>

<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
&nbsp;



<h1>Sender Name: {{transmission_details.SenderName}}</h1>
<h2>ID: {{transmission_details.transmissionid}}</h2>
<h2>Benefit Administrator Platform: {{transmission_details.BenefitAdministratorPlatform}}</h2>
<h2>Receiver Name: {{transmission_details.ReceiverName}}</h2>
<h2>Test Production Code: {{transmission_details.TestProductionCode}}</h2>
<h2>Transmission Type Code: {{transmission_details.TransmissionTypeCode}}</h2>
<h2>System Version Identifier: {{transmission_details.SystemVersionIdentifier}}</h2>
<h2>Created On: {{transmission_details.create_date}}</h2>
<h2>Created By: {{transmission_details.creator}}</h2>
<h2>Origin: {{transmission_details.source}}</h2>
<h2>ODS Connection: {{transmission_details.backend_SOR_connection}}</h2>
<h2>Commit Indicator: {{transmission_details.commit_indicator}}</h2>
<h2>Record Status: {{transmission_details.record_status}}</h2>
<h2>Response: {{transmission_details.response}}</h2>

{% for message in messages %}

        <div class="alert alert-success">
            <a class="close" href="#" data-dismiss="alert">×</a>

            {{ message }}

        </div>
{% endfor %}

{% endblock %}

intellidata/transmissions/templates/transmissions/transmission_list.html
{% extends "transmissions/transmission_base.html" %}

{% load static %}
{% load thumbnail %}

{% block pretransmission %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome
			{{user.username }}

		</h2>

    {% endif %}
		<h2>Transmissions</h2>

		{% if not object_list %}
  			<p>No transmissions available at this time! Go ahead and create a transmission if needed!</p>
		{% else %}
				<p>Welcome to the transmissions Page! Select a transmission that you want to work with!</p>
		{% endif %}

	</div>

	{% if user.is_authenticated %}


	<div class="dropdown">
	  <button class="dropbtn btn btn-primary btn-large">Manage Transmissions</button>
	  <div class="dropdown-content">

		<a href="{% url 'transmissions:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New transmission!</a>
		&nbsp;
		<a href="{% url 'transmissions:bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Upload transmissions!</a>
		&nbsp;
		<a href="{% url 'transmissions:export_transmissions' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span>Download Transmissions!</a>
		&nbsp;
		<a href="{% url 'transmissions:feederrors' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-fire"></span>View Feed Errors</a>
		&nbsp;
	  <a href="{% url 'transmissions:bulksor' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Upload To ODS!</a>

	  </div>
	</div>

  &nbsp;
	<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
  &nbsp;

	<!--
	<a href="{% url 'transmissions:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New transmission!</a>
	&nbsp;
	<a href="{% url 'transmissions:bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Upload transmissions!</a>
	&nbsp;
-->
	{% if FileNotFound %}
    <div id="some_flag" title="Some Flag">
        <h2>File Does Not Exist!</h2>
    </div>
	{% endif %}

	{% endif %}
</div>
{% endblock %}

{% block transmission_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for transmission in object_list %}
			<a class="list-group-item" href="{% url 'transmissions:single' pk=transmission.pk %}">
			     <h3 class="title list-group-item-heading">Sender Name: {{ transmission.SenderName }}</h3>
					 <h3 class="title list-group-item-heading">ID: {{ transmission.transmissionid }}</h3>

					 <br>
					  <h4 class="title list-group-item-heading">Benefit Admin Platform: {{ transmission.BenefitAdministratorPlatform}}</h4>
					 <h4 class="title list-group-item-heading">Created On: {{ transmission.create_date }}</h4>
					 <h4 class="title list-group-item-heading">Created By: {{ transmission.creator }}</h4>
					 <h4 class="title list-group-item-heading">Bulk Upload Indicator: {{ transmission.bulk_upload_indicator }}</h4>

					 <br>
			<div class="list-group-item-text container-fluid">
				{{ transmission.description_html|safe }}
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}