intellidata/Accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse

app_name = 'Accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="Accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"editprofile/(?P<pk>\d+)/$", views.EditProfile.as_view(), name="editprofile"),
]

intellidata/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^employee/nonstandard/fileupload/$", views.EmployeeNonStdUpload.as_view(), name="nonstandardemployeefile"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^employees/", include("employees.urls", namespace="employees")),
    url(r"^employers/",include("employers.urls", namespace="employers")),
    url(r"^transmissions/",include("transmissions.urls", namespace="transmissions")),
    url(r"^events/",include("events.urls", namespace="events")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
    url(r"^bulkuploads/",include("bulkuploads.urls", namespace="bulkuploads")),
    url(r"^apicodes/",include("apicodes.urls", namespace="apicodes")),
    url(r"^emails/",include("emails.urls", namespace="emails")),
    url(r"^mandatories/",include("mandatories.urls", namespace="mandatories")),
    url(r"^numchecks/",include("numchecks.urls", namespace="numchecks")),
]

intellidata/emails/urls.py
from django.conf.urls import url

from . import views

app_name = 'emails'

urlpatterns = [
    url(r"^$", views.ListEmails.as_view(), name="all"),
    url(r"^new/$", views.CreateEmail.as_view(), name="create"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmail, name="version"),
    url(r"^search/$", views.SearchEmailForm, name="search"),
    url(r"^search/results/$", views.SearchEmailList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleEmail.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmail.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmail.as_view(),name="delete"),
]

intellidata/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
    			<div class="container">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
            &nbsp;
            <a class="navbar-brand mynav" href="{% url 'admin' %}">Admin</a>
            &nbsp;
            <a class="navbar-brand mynav" href="http://127.0.0.1:8000/admin/dashboard/mydash/">Dashboard</a>

            <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}

                      <div class="dropdown">
                        <li><a class="navbar-brand mynav" href="#" class="btn btn-simple">Search</a></li>
                        <div class="dropdown-content">

                          <li><a class="navbar-brand mynav" href="{% url 'employers:search' %}" class="btn btn-simple">Employer</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'employees:search' %}" class="btn btn-simple">Employee</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Product</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'agreements:search' %}" class="btn btn-simple">Agreement</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'transmissions:search' %}" class="btn btn-simple">Transmission</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'mandatories:search' %}" class="btn btn-simple">Mandatory Rule</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'numchecks:search' %}" class="btn btn-simple">Numeric Rule</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'events:search' %}" class="btn btn-simple">Event</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'emails:search' %}" class="btn btn-simple">Roles & Emails</a></li>


                        </div>
                      </div>

                      &nbsp;
                      &nbsp;

                      &nbsp;

                      <div class="dropdown">
                        <li><a class="navbar-brand mynav" href="#" class="btn btn-simple">Rules</a></li>
                        <div class="dropdown-content">
                            <li><a class="navbar-brand mynav" href="{% url 'mandatories:all' %}" class="btn btn-simple">Mandatory</a></li>
                            <li><a class="navbar-brand mynav" href="{% url 'numchecks:all' %}" class="btn btn-simple">Numeric</a></li>
                            <li><a class="navbar-brand mynav" href="{% url 'apicodes:all' %}" class="btn btn-simple">API Codes</a></li>

                        </div>
                      </div>

                      <li><a class="navbar-brand mynav" href="{% url 'employers:all' %}" class="btn btn-simple">Employers</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'employees:all' %}" class="btn btn-simple">Employees</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'agreements:all' %}" class="btn btn-simple">Agreements</a></li>


                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:editprofile' pk=user.pk %}">MyProfile</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
        </div>
    	</nav>
    </div>

    <br>
    <br>
    <br>
    <br>

        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/black.png" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

<script
src="http://code.jquery.com/jquery-3.1.1.js"
integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

 <script src="{% static "simplesocial/js/product_table.js"%}" type="text/javascript" ></script>


</html>

intellidata/templates/base0.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'groups:search' %}" class="btn btn-simple">Search Group</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:search' %}" class="btn btn-simple">Search Member</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Search Product</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    	</nav>
    </div>

        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

</html>

intellidata/templates/base1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data1</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
    			<div class="container">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
            <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:all' %}" class="btn btn-simple">Members</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'groups:search' %}" class="btn btn-simple">Search Group</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'members:search' %}" class="btn btn-simple">Search Member</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Search Product</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
        </div>
    	</nav>
    </div>

    <br>
    <br>
    <br>
    <br>

        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

      <style>
          body {
            background-image: url('{% static "images/darknewyorkcity.jpg" %}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            overflow: scroll;
          }
      </style>

<canvas id="canvas"></canvas>

<script
src="http://code.jquery.com/jquery-3.1.1.js"
integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>  -->

</html>

intellidata/templates/fileupload_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

<h3>Uplod a file</h3>

  <form method="POST" enctype="multipart/form-data">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Save" class="btn btn-primary btn-large">
    &nbsp;
    <a href="{% url 'test' %}" class="btn btn-primary btn-large">Cancel</a>
  </form>

intellidata/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Intelli Data</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">


  </head>


  <body data-spy="scroll" data-target=".navbar">
    <div class="navigation">
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation" id="navbar">
    			<div class="container">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand mynav" href="{% url 'home' %}">Home</a>
            <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a class="navbar-brand mynav" href="{% url 'employers:all' %}" class="btn btn-simple">Employers</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'employees:all' %}" class="btn btn-simple">Employees</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'products:all' %}" class="btn btn-simple">Products</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'agreements:all' %}" class="btn btn-simple">Agreements</a></li>

                      <div class="dropdown">
                        <li><a class="navbar-brand mynav" href="#" class="btn btn-simple">Search</a></li>
                        <div class="dropdown-content">

                          <li><a class="navbar-brand mynav" href="{% url 'employers:search' %}" class="btn btn-simple">Employer</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'employees:search' %}" class="btn btn-simple">Employee</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'products:search' %}" class="btn btn-simple">Product</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'agreements:search' %}" class="btn btn-simple">Agreement</a></li>
                          <li><a class="navbar-brand mynav" href="{% url 'transmissions:search' %}" class="btn btn-simple">Transmission</a></li>

                        </div>
                      </div>

                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:logout' %}">Log out</a></li>
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:editprofile' %}">Edit Profile</a></li>
    						{% else %}
    						  <!--    <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li> -->
                      <li><a class="navbar-brand mynav" href="{% url 'Accounts:login' %}">Log in</a></li>
    						      <li><a class="navbar-brand mynav" href="{% url 'Accounts:signup' %}">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
        </div>
    	</nav>
    </div>

    <br>
    <br>
    <br>
    <br>

        <div class="container mycontent">

          <h1>Welcome to IntelliDataSmart!</h1>
          <h2>A smart data exchange platform for modern businesses!</h2>
          <h2>Login or Sign-up to get started!</h2>

      <!--    <img src="{% static "images/background.png" %}" alt="Image not available!">  -->

        </div>


<!-- corona tag -->
<canvas id="canvas"></canvas>
<canvas id="orbits"></canvas>


  </body>
<!--  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> -->
<div class="container corona">
 <script src="{% static "simplesocial/js/corona.js"%}" type="text/javascript" ></script>
</div>

</html>

intellidata/templates/messages.html
{% extends "base.html" %}
{% block content %}

            <div class="alert alert-success">
                <a class="close" href="#" data-dismiss="alert">×</a>

                 {{ messages }}

            </div>

            &nbsp;

            <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">

{% endblock %}

intellidata/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in! {{user.username }}</h1>
  <br>
  <h3>Let's get started! You can either click on one of the below links to perform one of those activities, or you can click on one of the links in the top bar to view or manage those entities!</h3>

    <br>
  <h2><a href="{% url 'transmissions:all'%}">Set up a Transmission or view existing Transmissions</a></h2>
  <h2><a href="{% url 'products:all'%}">Set up a Product or view existing Products</a></h2>
  <h2><a href="{% url 'events:all'%}">View event log</a></h2>



</div>

{% endblock %}

intellidata/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}