intellidata/IntelliDataSmart/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from controlcenter.views import controlcenter
from django.urls import reverse

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^landing/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^employee/nonstandard/fileupload/$", views.EmployeeNonStdUpload.as_view(), name="nonstandardemployeefile"),
    url(r"^gotoadmin/$", views.GotoAdmin, name="admin"),
    url(r"^admin/", admin.site.urls),
    url(r"^admin/dashboard/", controlcenter.urls),
    url(r"^accounts/", include("Accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^employees/", include("employees.urls", namespace="employees")),
    url(r"^employers/",include("employers.urls", namespace="employers")),
    url(r"^transmissions/",include("transmissions.urls", namespace="transmissions")),
    url(r"^events/",include("events.urls", namespace="events")),
    url(r"^products/",include("products.urls", namespace="products")),
    url(r"^agreements/",include("agreements.urls", namespace="agreements")),
    url(r"^bulkuploads/",include("bulkuploads.urls", namespace="bulkuploads")),
    url(r"^apicodes/",include("apicodes.urls", namespace="apicodes")),
    url(r"^emails/",include("emails.urls", namespace="emails")),
    url(r"^mandatories/",include("mandatories.urls", namespace="mandatories")),
    url(r"^numchecks/",include("numchecks.urls", namespace="numchecks")),
]

intellidata/emails/urls.py
from django.conf.urls import url

from . import views

app_name = 'emails'

urlpatterns = [
    url(r"^$", views.ListEmails.as_view(), name="all"),
    url(r"^new/$", views.CreateEmail.as_view(), name="create"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmail, name="version"),
    url(r"^search/$", views.SearchEmailForm, name="search"),
    url(r"^search/results/$", views.SearchEmailList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleEmail.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmail.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmail.as_view(),name="delete"),
]

intellidata/employees/urls.py
from django.conf.urls import url

from . import views

app_name = 'employees'

urlpatterns = [
    url(r"^$",views.ListEmployees.as_view(),name='all'),
    url(r"^(?P<pk>\d+)/$",views.SingleEmployee.as_view(),name='single'),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmployee, name="version"),
    url(r"^search/$", views.SearchEmployeesForm, name="search"),
    url(r"^search/results/$", views.SearchEmployeesList.as_view(), name="search_results"),
    url(r"^(?P<pk>\d+)/create/$",views.CreateEmployee.as_view(),name='create'),
    url(r"^(?P<pk>\d+)/employee/error/$",views.ViewEmployeeErrorList.as_view(), name='feederrors'),
    url(r"^employee/error/$",views.ViewEmployeeErrorFullList.as_view(), name='feederrorsfull'),
    url(r"^(?P<pk>\d+)/upload/$",views.BulkUploadEmployee, name='upload'),
    url(r"^upload/nonstandard/$",views.NonStdBulkUploadEmployee,name="spl_bulk"),
    url(r"^upload/nonstandard/refresh/$",views.NonStdRefresh,name="refresh"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmployee.as_view(),name='update'),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmployee.as_view(),name='delete'),
    url(r"^email/(?P<pk>\d+)/$",views.EmailEmployee, name='email'),
    url(r"^subscribe/(?P<pk>\d+)/$",views.SubscribeEmployee, name='subscribe'),
    url(r"^text/(?P<pk>\d+)/$",views.TextEmployee, name='text'),
    url(r"^rest/employeelist/$",views.EmployeeList, name="rest"),
    url(r"^(?P<pk>\d+)/rest/employeelist/$",views.EmployeeListByEmployer, name="byemployer"),
    url(r"^ods/refresh/(?P<pk>\d+)/$", views.RefreshEmployee, name="refresh"),
    url(r"^loadods/$",views.BulkUploadSOR,name="bulksor"),
    url(r"^ods/pull/(?P<pk>\d+)/$",views.BackendPull, name="backendpull"),
    url(r"^ods/history/(?P<pk>\d+)/$", views.ListEmployeesHistory, name="history"),
    url(r"^TDS/export/$",views.ExportEmployeeDataToCSV,name="employees_download"),
]

intellidata/employers/urls.py
from django.conf.urls import url

from . import views

app_name = 'employers'

urlpatterns = [
    url(r"^$", views.ListEmployers.as_view(), name="all"),
    url(r"^create/$",views.CreateEmployer.as_view(),name='create'),
    url(r"^upload/standard/$",views.BulkUploadEmployer,name="bulk"),
    url(r"^upload/nonstandard/$",views.NonStdBulkUploadEmployer,name="spl_bulk"),
    url(r"^upload/nonstandard/refresh/$",views.NonStdRefresh,name="refresh"),
    url(r"^version/(?P<pk>\d+)/$",views.VersionEmployer, name="version"),
    url(r"^search/$", views.SearchEmployersForm, name="search"),
    url(r"^search/results/$", views.SearchEmployersList.as_view(), name="search_results"),
    url(r"^posts/in/(?P<pk>\d+)/$",views.SingleEmployer.as_view(),name="single"),
    url(r"^update/(?P<pk>\d+)/$",views.UpdateEmployer.as_view(),name="update"),
    url(r"^delete/(?P<pk>\d+)/$",views.DeleteEmployer.as_view(),name="delete"),
    url(r"^rest/employerlist/$",views.EmployerList, name="rest"),
    url(r"^(?P<pk>\d+)/rest/employerlist/$",views.EmployerListByTransmission, name="bytransmission"),
    url(r"^ods/history/(?P<pk>\d+)/$", views.ListEmployersHistory, name="history"),
    url(r"^ods/refresh/(?P<pk>\d+)/$", views.RefreshEmployer, name="refresh"),
    url(r"^bulkuploadods/$",views.BulkUploadSOR,name="bulksor"),
    url(r"^ods/pull/(?P<pk>\d+)/$",views.BackendPull, name="backendpull"),
    url(r"^employer/error/$",views.ViewEmployerErrorList.as_view(), name='feederrors'),
    url(r"^(?P<pk>\d+)/employees/show/$", views.ShowEmployeesList.as_view(), name="show_employees"),
    url(r"^(?P<pk>\d+)/agreements/show/$", views.ShowAgreementsList.as_view(), name="show_agreements"),
    url(r"^TDS/export/$",views.ExportEmployerDataToCSV,name="employers_download"),

]

intellidata/employers/views.py
from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponseForbidden
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.decorators import user_passes_test
import time
from django.db.models import Q
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from django.db.models import Count
from employees.models import Employee, EmployeeSerializer, EmployeeErrorSerializer
from employers.models import Employer, EmployerSerializer, EmployerErrorSerializer
from django.contrib.auth.models import User
from bulkuploads.models import BulkUpload
from apicodes.models import APICodes
from employers.models import Employer
from employers.models import EmployerError
from employers.models import EmployerErrorAggregate
from . import models
from . import forms
from employers.forms import EmployerForm
from bulkuploads.forms import BulkUploadForm
import csv
from employers.utils import BulkCreateManager, Notification
from employers.utils import ApiDomains
import os
import os.path
from os import path
from django.utils.text import slugify
import misaka
import uuid
from django.shortcuts import get_object_or_404
from transmissions.models import Transmission
from mandatories.models import Mandatory
from numchecks.models import Numcheck
from django.utils.encoding import smart_str

import boto3
import requests
import json
import re
from botocore.exceptions import NoCredentialsError
import io
from django.db.models import Count
from datetime import datetime

from events.forms import EventForm
from events.models import Event
from botocore.errorfactory import ClientError
from collections import defaultdict

# For Rest rest_framework
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from employers.serializers import EmployerSerializer

from rest_framework import serializers

class SingleEmployer(LoginRequiredMixin, generic.DetailView):
    context_object_name = 'employer_details'
    model = models.Employer
    template_name = 'employers/employer_detail.html'


class ListEmployers(LoginRequiredMixin, generic.ListView):
    model = models.Employer
    template_name = 'employers/employer_list.html'

    def get_queryset(self):
        return models.Employer.objects.all()
        #return models.Employer.objects.prefetch_related('transmission')
        #return models.employer.objects.get(user=request.user)

class CreateEmployer(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
#    fields = ("name", "description")
    permission_required = 'employers.add_employer'
    context_object_name = 'employer_details'
    redirect_field_name = 'employers/employer_list.html'
    form_class = forms.EmployerForm
    model = models.Employer
    template_name = 'employers/employer_form.html'

    def form_valid(self, form):
        if not self.request.user.has_perm('employers.add_employer'):
            raise HttpResponseForbidden()
        else:
            #form.instance.transmission = self.transmission
            form.instance.creator = self.request.user
            form.instance.record_status = "Created"
            form.instance.source = "Online Transaction"
            if form.instance.transmission == None:
                form.instance.transmissionid = "Unknown"
            else:
                form.instance.transmissionid=form.instance.transmission.transmissionid

            return super().form_valid(form)



#Pull from  backend system of record(SOR)
@permission_required("employers.add_employer")
@login_required
def BackendPull(request, pk):
        # fetch the object related to passed id
        #url = 'https://94q78vev60.execute-api.us-east-1.amazonaws.com/Prod/intellidataEmployerAPI/latest'

        prod_obj = get_object_or_404(Employer, pk = pk)

        api = ApiDomains()
        url = api.employer + "/" + "latest"
        payload={'ident': prod_obj.employerid}
        resp = requests.get(url, params=payload)
        print(resp.text)
        print(resp.status_code)
        obj = get_object_or_404(APICodes, http_response_code = resp.status_code)
        status_message=obj.http_response_message
        mesg=str(resp.status_code) + " - " + status_message
        if resp.status_code != 200:
            # This means something went wrong.
            #raise ApiError('GET /tasks/ {}'.format(resp.status_code))
            #raise APIError(resp.status_code)
            message={'messages':mesg}
            return render(request, "messages.html", context=message)
        else:
            json_data = json.loads(resp.text)

            # fetch the object related to passed id
            #obj = get_object_or_404(Employer, pk = json_data["LOCAL_ID"])

            # pass the object as instance in form
            #form = EmployerForm(request.POST or None, instance = obj)

            #OVERRIDE THE OBJECT WITH API data
            obj.pk = int(json_data["LOCAL_ID"])
            obj.employerid = json_data["EMPLOYER_ID"]
            obj.name = json_data["NAME"]
            obj.slug = json_data["SLUG"]
            obj.description = json_data["DESCRIPTION"]
            obj.description_html = misaka.html(obj.description)
            obj.FederalEmployerIdentificationNumber = json_data["FEDERAL_EMPLOYER_IDENTIFICATION_NUMBER"]
            obj.CarrierMasterAgreementNumber = json_data["CARRIER_MASTER_AGREEMENT_NUMBER"]

            obj.address_line_1 = json_data["ADDRESS_LINE_1"]
            obj.address_line_2 = json_data["ADDRESS_LINE_2"]
            obj.city = json_data["CITY"]
            obj.state = json_data["STATE"]
            obj.zipcode = json_data["ZIPCODE"]

            obj.purpose = json_data["PURPOSE"]
            obj.planadmin_email = json_data["PLANADMIN_EMAIL"]

            obj.photo = json_data["PHOTO"]
            obj.creator = User.objects.get(pk=int(json_data["CREATOR"]))
            #obj.crerator = get_object_or_404(User, pk=obj.creatorid)
            obj.employer_date = json_data["EMPLOYER_DATE"]

            transmission_id = json_data["TRANSMISSION"]
            transmission_obj = get_object_or_404(Transmission, pk = transmission_id)
            obj.transmission = transmission_obj
            obj.source = json_data["SOURCE"]
            obj.transmissionid = json_data["TRANSMISSIONID"]

            obj.backend_SOR_connection = json_data["CONNECTION"]
            obj.response = json_data["RESPONSE"]
            obj.commit_indicator = json_data["COMMIT_INDICATOR"]
            obj.record_status = json_data["RECORD_STATUS"]

            context = {'employer_details':obj}

            return render(request, "employers/employer_detail.html", context=context)



#Pull from  backend system of record(SOR)
@permission_required("employers.add_employer")
@login_required
def ListEmployersHistory(request, pk):

                context ={}

                prod_obj = get_object_or_404(Employer, pk = pk)

                api = ApiDomains()
                url = api.employer + "/" + "history"
                #url = 'https://94q78vev60.execute-api.us-east-1.amazonaws.com/Prod/intellidataemployerAPI/history'
                payload={'ident': prod_obj.employerid}

                resp = requests.get(url, params=payload)
                print(resp.status_code)
                obj = get_object_or_404(APICodes, http_response_code = resp.status_code)
                status_message=obj.http_response_message
                mesg=str(resp.status_code) + " - " + status_message

                if resp.status_code != 200:
                    # This means something went wrong.
                    #raise ApiError('GET /tasks/ {}'.format(resp.status_code))
                    #raise APIError(resp.status_code)
                    message={'messages':mesg}
                    return render(request, "messages.html", context=message)
                else:
                    json_data=[]
                    dict_data=[]
                    obj_data=[]
                    json_data = resp.json()
                    #json_data = defaultdict(lambda: -1, json_data)

                    #print(json_data[0])
                    #print(json_data[1])
                    for ix in range(len(json_data)):
                     obj = Employer()
                      #dict_data.append(json.loads(json_data[ix]))
                     obj.pk = int(json_data[ix]["LOCAL_ID"])
                     obj.employerid = json_data[ix]["EMPLOYER_ID"]
                     obj.name = json_data[ix]["NAME"]
                     obj.slug = json_data[ix]["SLUG"]
                     obj.description = json_data[ix]["DESCRIPTION"]
                     obj.description_html = misaka.html(obj.description)
                     obj.FederalEmployerIdentificationNumber = json_data[ix]["FEDERAL_EMPLOYER_IDENTIFICATION_NUMBER"]
                     obj.CarrierMasterAgreementNumber = json_data[ix]["CARRIER_MASTER_AGREEMENT_NUMBER"]

                     obj.address_line_1 = json_data[ix]["ADDRESS_LINE_1"]
                     obj.address_line_2 = json_data[ix]["ADDRESS_LINE_2"]
                     obj.city = json_data[ix]["CITY"]
                     obj.state = json_data[ix]["STATE"]
                     obj.zipcode = json_data[ix]["ZIPCODE"]

                     obj.purpose = json_data[ix]["PURPOSE"]
                     #obj.planadmin_email = json_data[ix]["PLANADMIN_EMAIL"]
                     obj.planadmin_email = json_data[ix].get("PLANADMIN_EMAIL")

                     obj.photo = json_data[ix]["PHOTO"]

intellidata/employers/templates/employers/employer_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block preemployer %}{% endblock %}
    {% block employer_content %}{% endblock %}
    {% block postemployer %}{% endblock %}
  </div>
</div>

{% endblock %}

intellidata/employers/templates/employers/employer_detail.html
{% extends "employers/employer_base.html" %}
{% load static %}
{% block preemployer %}

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Employer</button>
  <div class="dropdown-content">

    <a href="{% url 'employers:version' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Version employer</a>
    &nbsp;
    <a href="{% url 'employers:update' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-pencil"></span> Update employer</a>
    &nbsp;
    <a href="{% url 'employers:delete' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Delete employer</a>
    &nbsp;
    <a href="{% url 'employers:backendpull' pk=employer_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Pull From ODS</a>
    &nbsp;
    <a href="{% url 'employers:history' pk=employer_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> List History</a>
    &nbsp;
    <a href="{% url 'employers:refresh' pk=employer_details.pk %}" class="btn btn-primary btn-large"><span class="glyphicon glyphicon-cloud"></span> Refresh From ODS</a>
    &nbsp;
    <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
    &nbsp;

  </div>
</div>


<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Employees</button>
  <div class="dropdown-content">

    <a href="{% url 'employers:show_employees' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span>Show Members</a>
    &nbsp;
    <a href="{% url 'employees:create' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span>Add Members</a>
    &nbsp;
    <a href="{% url 'employees:upload' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-upload"></span>Upload Members</a>
    &nbsp;
    <a href="{% url 'employees:spl_bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-up"></span>Upload non-standard file!</a>
    &nbsp;
    <a href="{% url 'employees:refresh' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span>Ingest non-standard data!</a>
    &nbsp;
    <a href="{% url 'employees:bulksor' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-upload"></span>Load To ODS</a>
    &nbsp;
    <a href="{% url 'employees:feederrors' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-fire"></span>View Feed Errors</a>
    &nbsp;



  </div>
</div>

<div class="dropdown">
  <button class="dropbtn btn btn-primary btn-large">Manage Agreements</button>
  <div class="dropdown-content">

    <a href="{% url 'agreements:create' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create Agreement</a>
    &nbsp;
    <a href="{% url 'employers:show_agreements' pk=employer_details.pk %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Show Ageements</a>
    &nbsp;

  </div>
</div>

<input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
&nbsp;

<h1>{{employer_details.name}}</h1>
<h3>Employer PK: {{employer_details.pk}}</h3>
<h3>Employer ID: {{employer_details.employerid}}</h3>
<h3>Federal Employer Identification Number: {{employer_details.FederalEmployerIdentificationNumber}}</h3>
<h3>Carrier Master Agreement Number: {{employer_details.CarrierMasterAgreementNumber}}</h3>
<h3>Purpose: {{employer_details.purpose}}</h3>
<h3>Sender Name: {{employer_details.transmission}}</h3>
<h3>Transmission ID: {{employer_details.transmissionid}}</h3>
<h3>Created On: {{employer_details.employer_date}}</h3>
<h3>Created By: {{employer_details.creator}}</h3>
<h3>Employee Count: {{employer_details.employee_set.count}}</h3>
<h3>Email of Plan Admin: {{employer_details.planadmin_email}}</h3>

&nbsp;

<h3>Postal Address Line 1: {{employer_details.address_line_1}}</h3>
<h3>Postal Address Line 2: {{employer_details.address_line_2}}</h3>
<h3>Postal City: {{employer_details.city}}</h3>
<h3>Postal State: {{employer_details.state}}</h3>
<h3>Postal Zipcode: {{employer_details.zipcode}}</h3>

  &nbsp;
<h3>Orgin: {{employer_details.source}}</h3>
<h3>Bulk Upload Indicator: {{employer_details.bulk_upload_indicator}}</h3>
<h3>ODS Connection: {{employer_details.backend_SOR_connection}}</h3>
<h3>Commit Indicator: {{employer_details.commit_indicator}}</h3>
<h3>Record Status: {{employer_details.record_status}}</h3>
<h3>Response: {{employer_details.response}}</h3>
<br>
<br>
<div style="background-color: rgb(0, 0, 0, 0.5);" data-spy="scroll" data-target=".navbar">
  <div class="list-employer-item-text container-fluid">
    {{ employer_details.description_html|safe }}
  </div>
</div>

{% if employer_details.photo %}
  <img src="{{ employer_details.photo.url }}"/>
{% endif %}


{% endblock %}

<!--
<div class="content">


				{% if user in employer.members.all %}
					<a href="{% url 'employers:leave' slug=employer_details.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'employers:join' slug=employer_details.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

-->



<!--{% block employer_content %}

<div class="col-md-8">
	{% if employer.posts.count == 0 %}
	<h2>No posts in this employer yet!</h2>

	{% else %}

		{% for post in employer.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}-->

intellidata/employers/templates/employers/employer_form.html
{% extends "employers/employer_base.html" %}
{% load bootstrap3 %}

{% block employer_content %}
<h4>Edit Employer</h4>
  <!-- <form method="POST" action="{% url 'employers:create' %}" id="employerForm"> -->
  <form method="POST" enctype="multipart/form-data">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Save" class="btn btn-primary btn-large">
    &nbsp;
    <a href="{% url 'employers:all'%}" class="btn btn-primary btn-large">Cancel</a>
  </form>
{% endblock %}

intellidata/employers/templates/employers/employer_list.html
{% extends "employers/employer_base.html" %}

{% load static %}
{% load thumbnail %}

{% block preemployer %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome
			{{user.username }}

		</h2>

    {% endif %}
		<h2>employers</h2>

		{% if not object_list %}
  			<p>No employers available at this time! Go ahead and create an employer if needed!</p>
		{% else %}
				<p>Welcome to the employers Page! Select a employer that you want to work with!</p>
		{% endif %}

	</div>

	<div class="dropdown">
		<button class="dropbtn btn btn-primary btn-large">Manage Employers</button>
		 <div class="dropdown-content">
				<a href="{% url 'employers:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span>Create New!</a>
				&nbsp;
				<a href="{% url 'employers:bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-up"></span>Upload standard file!</a>
				&nbsp;
				<a href="{% url 'employers:spl_bulk' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-up"></span>Upload non-standard file!</a>
				&nbsp;
				<a href="{% url 'employers:refresh' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span>Ingest non-standard data!</a>
				&nbsp;
				<a href="{% url 'employers:employers_download' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-down"></span> Download Employers!</a>
				&nbsp;
				<a href="{% url 'employers:feederrors' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-fire"></span>View Errors</a>
				&nbsp;
				<a href="{% url 'employers:bulksor' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-arrow-up"></span>Upload To ODS!</a>
		 </div>
		 &nbsp;

		 <input type="button" class="btn btn-primary btn-large" value="Go back!" onclick="history.back()">
				{% if FileNotFound %}
			    <div id="some_flag" title="Some Flag">
			        <h2>File Does Not Exist!</h2>
			    </div>
				{% endif %}

	</div>
</div>

<br>



{% endblock %}



{% block employer_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for employer in object_list %}
			<a class="list-group-item" href="{% url 'employers:single' pk=employer.pk %}">
			     <h3 class="title list-group-item-heading">{{ employer.name }}</h3>
					 <br>

					 {% block postemployer %}
					{% if employer.photo %}
						{% thumbnail employer.photo "300" crop="center" as im %}
							 <img src="{{ employer.photo.url }}" width="{{ im.width }}" height="{{ im.height }}">
						{% endthumbnail %}
					{% endif %}
					{% endblock %}

					<br>
					<br>
					<h4 class="title list-group-item-heading">Employer ID: {{ employer.employerid }}</h4>
					<h4 class="title list-group-item-heading">Purpose: {{ employer.purpose }}</h4>
					<h4 class="title list-group-item-heading">Created On: {{ employer.employer_date }}</h4>
					<h4 class="title list-group-item-heading">Created By: {{ employer.creator }}</h4>
					<h4 class="title list-group-item-heading">Sender Name: {{ employer.transmission }}</h4>
					<h4 class="title list-group-item-heading">Bulk Upload Indicator: {{ employer.bulk_upload_indicator }}</h4>
			<div class="list-group-item-text container-fluid">

				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ employer.employee_set.count }}</span> member{{ employer.employee_set.count|pluralize }}
					</div>
				</div>
				<br>
					{{ employer.description_html|safe }}
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}